### ISSUE TITLE
Patch application non-intuitive

### ISSUE THREAD

**Issue by eddievhfan1984** [Andy2244/openwrt-package-builder#1]
I've been trying to compile Samba 4 using this tool, but the git diff used to apply patches is holding me up. I'm asked which files I want to patch using diff, but I have no idea what to enter to apply the patch to all the files, as there's no local files I can use a path for (according to a search in Windows Explorer), and there's no simple command I can use to just auto-apply the patch.

![2019-02-03](https://user-images.githubusercontent.com/13581189/52176589-c3757f80-2782-11e9-9f78-22160c1ef423.png)

**Comment by Andy2244** [comment]
It seems you tried to use the example `example-samba4.read-me.txt` as input and you seem to have uncommented the old github patch examples.
`#PATCHES_GITHUB="openwrt/luci#2071 openwrt/packages#6772 openwrt/packages#6940 openwrt/openwrt#1233"`

If all you want to try is compile samba4 against the 18.06.01 sdk try this config:
```
VERSION="18.06.1"
TARGET="mvebu"
SUBTARGET="cortexa9"

# build from custom extra feed
FEED_1="src-git extra https://github.com/Andy2244/openwrt-extra.git"
FEED_1_PACKAGES="samba4-server luci-app-samba4 wsdd2"
```

Change the TARGET/SUBTARGET to your routers.

**Comment by eddievhfan1984** [comment]
Actually, that patch line was uncommented as it appeared in the files I checked out. All I uncommented was the line to force the samba36 uninstallation before installing the other packages.

**Comment by Andy2244** [comment]
Thats strange in github the line is still commented in the example file, so it should not try to apply this old patch, since it was already merged, which is the problem you get there.
https://github.com/Andy2244/openwrt-package-builder/blob/master/example-samba4.read-me.txt
