### ISSUE TITLE
Where are the signatures?

### ISSUE THREAD

**Issue by eddievhfan1984** [Andy2244/openwrt-package-builder#2]
I've gotten the build successfully completed and started the hosting server, but when I try to update opkg, it complains because there isn't a signature file to check the packages against. Should it be created by the script, or is there an override in opkg I'm missing?

**Comment by Andy2244** [comment]
I had to disable package signing, since there was a problem back when i tested this. I could still install packages via luci, using the local custom feed url. Can you try via luci or do you only have cli?

PS: I will try retest this and try re-enable signing.

**Comment by eddievhfan1984** [comment]
Neither LuCi nor CLI/Bash works. It finds the package archive alright, but I can't get samba4-server to show up with "opkg info" after I update the lists.

**Comment by eddievhfan1984** [comment]
I found a temporary workaround: disable signature checking in the global configuration in LuCI just long enough to get everything installed.

**Comment by Andy2244** [comment]
ok it seems thats because signature checking is now enabled by default, so since i had to disable this for the builder there is an issue.

Will retest this and add a fix or update the readme, thanks for the report.

PS: It can also be bypassed by installing the package directly by url or path (after scp).

**Comment by Andy2244** [comment]
ok the segfault was fixed at some point, so i could enable package signing now. This solves the problem and the Packages.sig file is now created.
